import type { SyncConfig, SyncResult, ChangedFile, PullRequestData, DocumentationImpact } from '@ghost-docs/types';
import { ChangeAnalyzer } from './change-analyzer.js';
import { DocumentationImpactAnalyzer } from './documentation-impact-analyzer.js';
import { PatchGenerator } from './patch-generator.js';
import { GitHubAdapter } from './github-adapter.js';
import { extractKnowledge } from '@ghost-docs/intelligence-engine';

import simpleGit from 'simple-git';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

export class DocumentationSynchronizer {
  private changeAnalyzer = new ChangeAnalyzer();
  private impactAnalyzer = new DocumentationImpactAnalyzer();
  private patchGenerator = new PatchGenerator();

  async sync(config: SyncConfig): Promise<SyncResult> {
    const git = simpleGit(config.repoPath);

    const diffSummary = await git.diffSummary(['HEAD~1']);
    const diffFiles = await git.diff(['HEAD~1', '--name-status']);

    const changedFiles: ChangedFile[] = diffSummary.files
      .filter((f): f is typeof f & { insertions: number; deletions: number } => 'insertions' in f && 'deletions' in f)
      .map((f) => ({
        path: f.file,
        status: this.mapStatus(f.file, diffFiles),
        additions: f.insertions,
        deletions: f.deletions,
      }));

    const analysis = this.changeAnalyzer.analyze(changedFiles);

    const kg = await extractKnowledge({ repoUrl: config.repoPath });
    const impacts = this.impactAnalyzer.analyze(analysis, kg);

    const patches = await this.generatePatches(impacts, kg, analysis, config.repoPath);

    const avgConfidence =
      impacts.length > 0
        ? impacts.reduce((s, i) => s + i.confidence, 0) / impacts.length
        : 0;

    let pullRequest: PullRequestData | undefined;

    if (!config.dryRun && config.githubToken && config.repoUrl && patches.length > 0) {
      pullRequest = await this.createPR(config, analysis, impacts, patches);

      const url = config.repoUrl || '';
      const match = url.match(/github\.com[:/]([\w.-]+)\/([\w.-]+?)(?:\.git)?$/);
      if (match) {
        const adapter = new GitHubAdapter({
          token: config.githubToken,
          owner: match[1],
          repo: match[2].replace('.git', ''),
        });

        try {
          await adapter.createBranch(config.baseBranch || 'main', pullRequest.branch);
          await adapter.commitFiles(pullRequest.branch, pullRequest.title, patches);
          const prUrl = await adapter.createPR(pullRequest);
          pullRequest.body += `\n\n🔗 ${prUrl}`;
        } catch {
          // Branch may already exist or PR creation fails silently in preview
        }
      }
    }

    return {
      analysis,
      impacts,
      patches,
      pullRequest,
      confidence: Math.round(avgConfidence * 100) / 100,
    };
  }

  private mapStatus(filePath: string, rawDiff: string): ChangedFile['status'] {
    for (const line of rawDiff.split('\n')) {
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 2 && parts[1] === filePath) {
        const status = parts[0];
        if (status === 'A') return 'added';
        if (status === 'D') return 'deleted';
        if (status === 'R' || status.startsWith('R')) return 'renamed';
        return 'modified';
      }
    }
    return 'modified';
  }

  private async generatePatches(
    impacts: DocumentationImpact[],
    kg: any,
    analysis: any,
    repoPath: string,
  ): Promise<any[]> {
    const patches = [];

    for (const impact of impacts) {
      if (impact.suggestedAction === 'no-change') continue;

      let currentContent = '';
      try {
        currentContent = await readFile(join(repoPath, impact.filePath), 'utf-8');
      } catch {
        currentContent = '';
      }

      const patch = this.patchGenerator.generate(impact, kg, currentContent, analysis);
      patches.push(patch);
    }

    return patches;
  }

  private async createPR(
    config: SyncConfig,
    analysis: any,
    impacts: any[],
    patches: any[],
  ): Promise<PullRequestData> {
    const branchName = `ghost-docs/sync-${Date.now()}`;
    const lines: string[] = [];

    lines.push('## Summary');
    lines.push(`This PR synchronizes documentation after ${analysis.summary}.`);
    lines.push('');
    lines.push('## Changes');
    for (const impact of impacts) {
      lines.push(`- **${impact.docType}** (\`${impact.filePath}\`): ${impact.reason}`);
    }
    lines.push('');
    lines.push('## Generated By');
    lines.push('Ghost Docs Documentation Synchronization Engine');

    const totalAdditions = patches.reduce((s: number, p: any) => s + p.additions, 0);
    const totalDeletions = patches.reduce((s: number, p: any) => s + p.deletions, 0);

    return {
      title: `docs: synchronize documentation after ${analysis.summary}`,
      body: lines.join('\n'),
      branch: branchName,
      base: config.baseBranch || 'main',
      files: patches.map((p: any) => p.filePath),
      confidence: totalAdditions + totalDeletions > 0 ? 0.85 : 0.3,
    };
  }
}
