import type { DocumentationImpact, KnowledgeGraph, DocumentationPatch, ChangeAnalysis } from '@ghost-docs/types';
import { MarkerParser } from './marker-parser.js';
import { generateExplainReport } from '@ghost-docs/docs';

export class PatchGenerator {
  private markerParser = new MarkerParser();

  generate(
    impact: DocumentationImpact,
    kg: KnowledgeGraph,
    currentContent: string,
    analysis: ChangeAnalysis,
  ): DocumentationPatch {
    const generated = this.buildSection(impact, kg, analysis);
    const patchedContent = this.markerParser.updateWithinMarkers(currentContent, generated);
    const additions = this.countLines(generated);
    const deletions = this.markerParser.hasMarkers(currentContent)
      ? this.countLines(this.markerParser.findMarkers(currentContent)?.existingContent || '')
      : 0;

    return {
      filePath: impact.filePath,
      originalContent: currentContent,
      patchedContent,
      additions,
      deletions,
      affectedSections: [impact.docType],
    };
  }

  private buildSection(impact: DocumentationImpact, kg: KnowledgeGraph, analysis: ChangeAnalysis): string {
    const lines: string[] = [];

    switch (impact.docType) {
      case 'README':
        lines.push(generateExplainReport(kg));
        break;

      case 'CHANGELOG':
        lines.push('## Changed');
        lines.push('');
        lines.push(`- ${analysis.summary}`);
        if (analysis.hasBreaking) lines.push('- ⚠️ Breaking changes');
        if (analysis.hasApiChanges) lines.push('- 🔄 API changes');
        if (analysis.hasDepChanges) lines.push('- 📦 Dependency updates');
        lines.push('');
        lines.push(`_Auto-generated by Ghost Docs_`);
        break;

      case 'API_REFERENCE':
        lines.push(`## API Reference`);
        lines.push('');
        for (const api of kg.apis) {
          lines.push(`### ${api.type.toUpperCase()}${api.framework ? ` (${api.framework})` : ''}`);
          lines.push('');
          lines.push(`- Base path: \`${api.path}\``);
          lines.push('');
        }
        lines.push(`_Auto-generated by Ghost Docs_`);
        break;

      case 'INSTALLATION_GUIDE':
        lines.push(`## Installation`);
        lines.push('');
        if (kg.commands.length > 0) {
          const installCmd = kg.commands.find((c) => c.name === 'install');
          const buildCmd = kg.commands.find((c) => c.name === 'build');
          if (installCmd) lines.push(`\`\`\`bash\n${installCmd.command}\n\`\`\``);
          if (buildCmd) lines.push(`\`\`\`bash\n${buildCmd.command}\n\`\`\``);
        }
        if (kg.dependencies.total > 0) {
          lines.push('');
          lines.push(`Requires ${kg.dependencies.total} dependencies`);
        }
        lines.push('');
        lines.push(`_Auto-generated by Ghost Docs_`);
        break;

      case 'ARCHITECTURE':
        lines.push(`## Architecture`);
        lines.push('');
        lines.push(kg.project_summary);
        if (kg.modules.length > 0) {
          lines.push('');
          lines.push('### Modules');
          for (const mod of kg.modules) {
            if (mod.name !== 'root') {
              lines.push(`- \`${mod.path}/\` — ${mod.responsibilities.join(', ')}`);
            }
          }
        }
        lines.push('');
        lines.push(`_Auto-generated by Ghost Docs_`);
        break;

      default:
        lines.push(`_Auto-generated content for ${impact.docType}_`);
        break;
    }

    return lines.join('\n');
  }

  private countLines(content: string): number {
    if (!content) return 0;
    return content.split('\n').filter((l) => l.trim().length > 0).length;
  }
}
